#!/usr/bin/env zsh

[[ $1 == "clean" ]] && CLEAN="clean"
xcodebuild build $CLEAN \
    -workspace AdoreMe.xcworkspace \
    -scheme "AdoreMe" \
    -derivedDataPath "DerivedData" \
    -sdk iphonesimulator \
    -destination "platform=iOS Simulator,OS=13.7,name=iPhone 13.7" \
    ONLY_ACTIVE_ARCH=YES \
    CODE_SIGN_IDENTITY="" \
    CODE_SIGNING_REQUIRED=NO \
    | xcpretty

