#!/usr/bin/env zsh

is_git_folder || exit 1

TOP_LEVEL_DIR=$(git rev-parse --show-toplevel)

JIRA_NUMBER=$1
PROJECT="${2:-AMA}"


[[ $1 ]] || { print "${LIGHT_GREEN}JIRA issue number${NORMAL} not specified.\nUsage: branch ${LIGHT_GREEN}<JIRA_NUMBER>${NORMAL}\n"; exit ; }

#printf "Enter JIRA username: (mihai.cristescu@adoreme.com)"
#read USER
#[[ $USER ]] || { USER="mihai.cristescu@adoreme.com"; }
USER="mihai.cristescu@adoreme.com"
PASS=$(security find-generic-password -w -s 'JIRA_SCRIPTS' -a 'mihai.cristescu@adoreme.com')

print "Fetching JIRA issue: ${LIGHT_GREEN}$JIRA_NUMBER${NORMAL}"
TITLE=$(curl -s -u "${USER}:${PASS}" "https://adoreme.atlassian.net/rest/api/2/issue/$PROJECT-$JIRA_NUMBER?fields=summary" | jq -r .fields.summary)

[[ $TITLE ]] || { print "${LIGHT_GREEN}Could not get the issue title${NORMAL}\n"; exit ; }

print "\nIssue title: ${LIGHT_GREEN}$TITLE${NORMAL}\n"

TYPES=("FEATURE" "BUGFIX" "SPIKE" "TASK")
select BRANCH_TYPE in "${TYPES[@]}"; do
    break
done

TITLE_DASHED=$(echo ${TITLE} | sed -r "s/\[iOS\] //g" | sed -r "s/(\/|\?|\.|\*|\&|\(|\))//g" | sed -r "s/\ +/-/g" | sed -r "s/-+/-/g")

FINAL_BRANCH=${BRANCH_TYPE:l}/$PROJECT-${JIRA_NUMBER}-${TITLE_DASHED:l}
print "\nSwitching to branch:${LIGHT_GREEN} ${FINAL_BRANCH} ${NORMAL}?"
printf "Press a key to confirm or CTRL+C to cancel..."
read -k1 -s

git switch -c ${FINAL_BRANCH} develop

