#!/usr/bin/env zsh

heading "Cleaning git ignored files"

is_git_folder || exit 1

TOP_LEVEL_DIR="$(git rev-parse --show-toplevel)"
FILES=$(git -C $TOP_LEVEL_DIR clean -Xdffn | wc -l )

if (( FILES > 0 )); then
    git -C $TOP_LEVEL_DIR clean -Xdff
else
    print "${LIGHT_GREEN}* Nothing to clean.${NORMAL}"
fi
