#!/usr/bin/env zsh
# Note: This script requires that you have $GITHUB_TOKEN set.
# Get one here: https://github.com/settings/tokens

ORG=$1

HAS_NEXT=true
i=1

while $HAS_NEXT
do
    REPOS=$(curl "https://api.github.com/orgs/$ORG/repos?per_page=100&page=$i" \
        -H "Accept: application/vnd.github.machine-man-preview+json" \
        | jq -r ".[].ssh_url")

    if [[ -z "$REPOS" ]]
    then
        HAS_NEXT=false
    fi

    for REPO in ${(f)REPOS}; do
        FOLDER=$(basename $REPO .git)
        if [ -d "$FOLDER/.git" ]; then
            echo "Repo '$FOLDER' exists. Pulling latest changes..."
            git -C "$FOLDER" pull
        else
            echo "Cloning $REPO..."
            git clone $REPO
        fi
    done

    ((i++))
done
