#!/bin/bash
set -e

WORKING_DIR=$(pwd)
FRAMEWORK_FOLDER_NAME="TEMP_BUILD"
FRAMEWORK_NAME="pop"
FRAMEWORK_PATH="${WORKING_DIR}/${FRAMEWORK_NAME}.xcframework"
FRAMEWORK_ZIP_PATH="${WORKING_DIR}/${FRAMEWORK_NAME}.xcframework.zip"
BUILD_SCHEME="pop-ios-framework"

SIMULATOR_ARCHIVE_PATH="${WORKING_DIR}/${FRAMEWORK_FOLDER_NAME}/simulator.xcarchive"
IOS_DEVICE_ARCHIVE_PATH="${WORKING_DIR}/${FRAMEWORK_FOLDER_NAME}/iOS.xcarchive"
CATALYST_ARCHIVE_PATH="${WORKING_DIR}/${FRAMEWORK_FOLDER_NAME}/catalyst.xcarchive"

rm -rf "${FRAMEWORK_FOLDER_NAME}"
rm -rf "${FRAMEWORK_PATH}"

mkdir "${FRAMEWORK_FOLDER_NAME}"

echo "Created ${FRAMEWORK_FOLDER_NAME}"
echo "Archiving ${FRAMEWORK_NAME}"

xcodebuild archive ONLY_ACTIVE_ARCH=NO \
    -scheme ${BUILD_SCHEME} \
    -destination="generic/platform=iOS Simulator" \
    -archivePath "${SIMULATOR_ARCHIVE_PATH}" \
    -sdk iphonesimulator \
    SKIP_INSTALL=NO \
    BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -scheme ${BUILD_SCHEME} \
    -destination="generic/platform=iOS" \
    -archivePath "${IOS_DEVICE_ARCHIVE_PATH}" \
    -sdk iphoneos \
    SKIP_INSTALL=NO \
    BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -scheme ${BUILD_SCHEME} \
    -destination='generic/platform=macOS,variant=Mac Catalyst' \
    -archivePath "${CATALYST_ARCHIVE_PATH}" \
    SKIP_INSTALL=NO \
    BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

xcodebuild -create-xcframework \
    -framework ${SIMULATOR_ARCHIVE_PATH}/Products/Library/Frameworks/${FRAMEWORK_NAME}.framework \
    -framework ${IOS_DEVICE_ARCHIVE_PATH}/Products/Library/Frameworks/${FRAMEWORK_NAME}.framework \
    -framework ${CATALYST_ARCHIVE_PATH}/Products/Library/Frameworks/${FRAMEWORK_NAME}.framework \
    -output "${FRAMEWORK_PATH}"

rm -rf "${SIMULATOR_ARCHIVE_PATH}"
rm -rf "${IOS_DEVICE_ARCHIVE_PATH}"
rm -rf "${CATALYST_ARCHIVE_PATH}"
rm -rf "${FRAMEWORK_FOLDER_NAME}"

ditto -c -k --sequesterRsrc --keepParent ${FRAMEWORK_PATH} ${FRAMEWORK_ZIP_PATH}
echo $(swift package compute-checksum ${FRAMEWORK_ZIP_PATH})
open "${WORKING_DIR}"
