#!/usr/bin/env zsh

heading "Change Development Team in Xcode projects"
is_git_folder || exit 1

TEAM=${1:-"S8V3V9GFN2"}
find $(pwd) -name "project.pbxproj" -print -exec sed -i '' -e "s|\(DEVELOPMENT_TEAM = \).*\;|\1${TEAM}\;|g" {} \;
