#!/usr/bin/env zsh

heading "Change Development Environement"

ENVIRONMENTS=(
    'Production;https://www.adoreme.com'
    'DELTA 1;delta-1'
    'DELTA 2;delta-2'
    'DELTA 3;delta-3'
    'GAMMA 1;gamma-1'
    'GAMMA 2;gamma-2'
    'GAMMA 3;gamma-3'
    'SIGMA 1;sigma-1'
    'SIGMA 2;sigma-2'
    'SIGMA 3;sigma-3'
    'OMEGA 1;omega-1'
    'OMEGA 2;omega-2'
    'OMEGA 3;omega-3'
    'ALPHA 1;alpha-1'
    'ALPHA 2;alpha-2'
    'ALPHA 3;alpha-3'
    'CORE 1;core-1'
    'CORE 2;core-2'
    'CORE 3;core-3'
)
NAMES=()
BASEURLS=()

for ENVIRONMENT in $ENVIRONMENTS; do
    IFS=";" read -r -A arr <<< "${ENVIRONMENT}"
    NAMES=("${NAMES[@]}" "${arr[1]}")
    BASEURLS=("${BASEURLS[@]}" "${arr[2]}")
done

export COLUMNS=1

select NAME in $NAMES; do
    if [[ -n $NAME ]]; then
        break
    else
        print "Wrong selection."
    fi
done

ENVIRONMENT=${BASEURLS[$REPLY]}

if [[ "$REPLY" -eq "1" ]]; then
    BASE_URL="$ENVIRONMENT"
    WEB_URL="$ENVIRONMENT"
else
    BASE_URL="http://gw-main-ns-${ENVIRONMENT}.stg.adoreme.com"
    WEB_URL="http://adoreme-js-ns-${ENVIRONMENT}.stg.adoreme.com"
fi

#iOS
find ./Sources \
    -name "URLs.plist" \
    -print \
    -exec /usr/libexec/PlistBuddy \
    -c "Set :BaseUrl ${BASE_URL}" \
    {} \;

# Adnroid
PATTERN="\"BASE_URL\", \'\"\(.*\)\"\'"
REPLACE="\"BASE_URL\", \'\"${BASE_URL}\/\"\'"

find ../../android-app/app \
    -name "build.gradle" \
    -print \
    -exec sed -i "" -e "s|${PATTERN}|${REPLACE}|" \
    {} \;

