#!/usr/bin/env zsh

heading "Change Development Environement"

ENVIRONMENTS=(
    'Production;https://www.adoreme.com'
    'Delta 1;delta-1'
    'Delta 2;delta-2'
    'Delta 3;delta-3'
    'Gamma 1;gamma-1'
    'Gamma 2;gamma-2'
    'Gamma 3;gamma-3'
    'Sigma 1;sigma-1'
    'Sigma 2;sigma-2'
    'Sigma 3;sigma-3'
    'Omega 1;omega-1'
    'Omega 2;omega-2'
    'Omega 3;omega-3'
)
NAMES=()
BASEURLS=()

for ENVIRONMENT in $ENVIRONMENTS; do
    IFS=";" read -r -A arr <<< "${ENVIRONMENT}"
    NAMES=("${NAMES[@]}" "${arr[1]}")
    BASEURLS=("${BASEURLS[@]}" "${arr[2]}")
done
export COLUMNS=1
select NAME in $NAMES; do
    if [[ -n $NAME ]]; then
        break
    else
        print "Wrong selection."
    fi
done

ENVIRONMENT=${BASEURLS[$REPLY]}
BASE_URL="http://magento-ns-${ENVIRONMENT}.stg.adoreme.com"
FRONTEND_URL="http://adoreme-js-ns-${ENVIRONMENT}.stg.adoreme.com/?is_adoreme_webview=true"

#iOS
find Targets \
    -name "URLs.plist" \
    -print \
    -exec /usr/libexec/PlistBuddy \
    -c "Set :BaseUrl ${BASE_URL}" \
    -c "Set :FrontendWebUrl ${FRONTEND_URL}" \
    {} \;

# Adnroid

PATTERN="\"BASE_URL\", \'\"\(.*\)\"\'"
REPLACE="\"BASE_URL\", \'\"${BASE_URL}\/\"\'"

find ../android/app \
    -name "build.gradle" \
    -print \
    -exec sed -i "" -e "s|${PATTERN}|${REPLACE}|" \
    {} \;
