#!/usr/bin/env zsh

heading "Change Development Environement"

ENVIRONMENTS=(
    'Production;https://www.adoreme.com'
    'DELTA 1;delta-1'
    'DELTA 2;delta-2'
    'DELTA 3;delta-3'
    'GAMMA 1;gamma-1'
    'GAMMA 2;gamma-2'
    'GAMMA 3;gamma-3'
    'SIGMA 1;sigma-1'
    'SIGMA 2;sigma-2'
    'SIGMA 3;sigma-3'
    'OMEGA 1;omega-1'
    'OMEGA 2;omega-2'
    'OMEGA 3;omega-3'
)
NAMES=()
BASEURLS=()

for ENVIRONMENT in $ENVIRONMENTS; do
    IFS=";" read -r -A arr <<< "${ENVIRONMENT}"
    NAMES=("${NAMES[@]}" "${arr[1]}")
    BASEURLS=("${BASEURLS[@]}" "${arr[2]}")
done

export COLUMNS=1

select NAME in $NAMES; do
    if [[ -n $NAME ]]; then
        break
    else
        print "Wrong selection."
    fi
done

ENVIRONMENT=${BASEURLS[$REPLY]}

if [[ "$REPLY" -eq "1" ]]; then
    WEB_URL="$ENVIRONMENT"
else
    WEB_URL="http://adoreme-js-ns-${ENVIRONMENT}.stg.adoreme.com"
fi

open -a "Safari" $WEB_URL
open -a "Google Chrome" $WEB_URL
