#! /usr/bin/env zsh

TOP_LEVEL_DIR=$(git rev-parse --show-toplevel)
WORKDIRS=(${(@f)$(git -C $TOP_LEVEL_DIR worktree list --porcelain | grep worktree | awk '{print $2}')})
(( $#WORKDIRS == 1 )) && WORKDIRS=($TOP_LEVEL_DIR)
for WORKDIR in $WORKDIRS; do
    printf "${UNDERLINE}${BOLD}${BLUE}%b${NORMAL} " $WORKDIR
    pull_branch $WORKDIR
    SUBMODULES=(${(@f)$(git -C $WORKDIR config --file $WORKDIR/.gitmodules --get-regexp path | awk '{ print $2 }')})
    (( $#SUBMODULES == 0 )) && continue
    for SUBMODULE in $SUBMODULES; do
        printf "${UNDERLINE}${BOLD}${BLUE}%b${NORMAL} " $SUBMODULE
        pull_branch $WORKDIR/$SUBMODULE
    done
done
