#! /usr/bin/env zsh

heading "Cleaning ignored files"
TOP_LEVEL_DIR="$(git rev-parse --show-toplevel)"
FILES=$(git -C $TOP_LEVEL_DIR clean -xdfn -e Carthage/ | wc -l )
if (( FILES > 0 )); then
    git -C $TOP_LEVEL_DIR clean -xdf -e Carthage/
else
    printf "* Nothing to clean.\n"
fi