#!/usr/bin/env zsh

is_git_folder || exit 1

FILE=$(git rev-parse --show-toplevel)/PayAtPump/PayAtPump/CustomLocation.gpx
skip "$FILE"

LOCATIONS=()
NAMES=()
LATITUDINES=()
LONGITUDINES=()
LOCATIONS=(
    'Romania IBM Bucharest;44.4356676;26.0544182'
    'Romania IBM Brasov;45.6687406;25.6194894'
    'Holland Site;51.9386;4.1083'
    'Australia Site;-37.821067;144.966071'
    'US one car wash;41.264578;-96.161076'
)

for LOCATION in $LOCATIONS; do
    IFS=";" read -r -A arr <<< "${LOCATION}"
    NAMES=("${NAMES[@]}" "${arr[1]}")
    LATITUDINES=("${LATITUDINES[@]}" "${arr[2]}")
    LONGITUDINES=("${LONGITUDINES[@]}" "${arr[3]}")
done

select NAME in $NAMES; do
    if [[ -n $NAME ]]; then
        break
    else
        print "Wrong selection."
    fi
done

NAME=${NAMES[$REPLY]}
LAT=${LATITUDINES[$REPLY]}
LONG=${LONGITUDINES[$REPLY]}

cat <<EOF > "$FILE"
<?xml version="1.0"?>
<gpx version="1.1" creator="Xcode">
<wpt lat="$LAT" lon="$LONG"></wpt><!--Custom location: $NAME-->
</gpx>
EOF
