#!/usr/bin/env zsh

TOP_LEVEL_DIR=$1

if [[ -n "$1" ]]; then
    FILTER="$1"
    WORKDIRS=$(git -C $TOP_LEVEL_DIR worktree list | grep "$FILTER")
else
    WORKDIRS=$(git -C $TOP_LEVEL_DIR worktree list)
fi

WORKDIRS=(${(f)WORKDIRS})
COUNT=$#WORKDIRS

if (( COUNT == 0 )); then
    print "\n There are no wortrees.\n"
    return 1
fi

if (( COUNT == 1 )); then
    SELECTION_PATH=$(echo $WORKDIRS[1] | awk '{ print $1 }')
    cd $SELECTION_PATH
    return 0
fi

heading "Choose project worktree:"

select WORKDIR in $WORKDIRS; do
    if [[ -n "$WORKDIR" ]]; then
        SELECTION=$REPLY
        break
    fi
done

SELECTION_PATH=$(echo $WORKDIRS[SELECTION] | awk '{ print $1 }')

cd $SELECTION_PATH
return 0

