#!/usr/bin/env zsh

TICKET=$1

if [[ $TICKET ]]; then
    open "https://jira.adoreme.com/browse/AMA-$TICKET"
else
    open "https://jira.adoreme.com/secure/RapidBoard.jspa?rapidView=141&&quickFilter=412"
fi

