#!/usr/bin/env zsh

TICKET=$1

if [[ -n $TICKET ]]; then
    
else
    BRANCH=$(git branch --show-current)
    TICKET=$(echo $BRANCH | grep -oE '[0-9]+')
fi

PROJECT=${2:-AMA}

if [[ $TICKET ]]; then
    open "https://adoreme.atlassian.net/browse/$PROJECT-$TICKET"
else
    open "https://adoreme.atlassian.net/jira/software/c/projects/AMA/boards/14?quickFilter=27"
fi
