#! /usr/bin/env zsh

REPO_PATH=$1
[[ -d $REPO_PATH ]] || { echo "Repo path not valid!"; return 1 ; }
BRANCH_REF=$(git -C $REPO_PATH symbolic-ref -q HEAD)
if [[ -z $BRANCH_REF ]]; then
    printf "%bSkipping (detached state).%b\n" "${LIGHT_RED}" "${NORMAL}"
else
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    printf "${LIGHT_YELLOW}[%s]${NORMAL}\n" "$CURRENT_BRANCH"
    git -C $REPO_PATH fetch --all
    git -C $REPO_PATH pull
fi
printf "\n"
