#! /usr/bin/env zsh

heading "Recreating all files"

TOP_LEVEL_DIR=$(git rev-parse --show-toplevel 2>/dev/null )
[[ $TOP_LEVEL_DIR ]] || print "Not in a git folder. Exiting..." ; exit 1

git -C $TOP_LEVEL_DIR rm --cached -r .
git -C $TOP_LEVEL_DIR reset --hard
print ""

