#!/usr/bin/env zsh

heading "Recreating all git files"

is_git_folder || exit 1

TOP_LEVEL_DIR=$(git rev-parse --show-toplevel)

git -C $TOP_LEVEL_DIR rm --cached -r $TOP_LEVEL_DIR
git -C $TOP_LEVEL_DIR reset --hard

print ""
