#!/usr/bin/env zsh

is_git_folder || exit 1

TOP_LEVEL_DIR=$(git rev-parse --show-toplevel)

REF1=$1
REF2=$2

[[ $1 ]] || { print "${LIGHT_GREEN}Ref 1${NORMAL} not specified.\nUsage: release_diff ${LIGHT_GREEN}<ref1> <ref2>${NORMAL}\n"; exit ; }
[[ $2 ]] || { print "${LIGHT_GREEN}Ref 2${NORMAL} not specified.\nUsage: release_diff ${LIGHT_GREEN}<ref1> <ref2>${NORMAL}\n"; exit ; }

USER="delta"
PASS=$(security find-generic-password -w -s 'JIRA_SCRIPTS' -a "$USER")

REPOS=($TOP_LEVEL_DIR)

declare -a ISSUES_ARRAY
declare -a TITLES_ARRAY

# Make array with issues
{ for REPO in $REPOS; do
    git -C $REPO log $REF1..$REF2 --no-merges --oneline
   done
} | grep -oE "(AMA-\d+|PN-\d+)" \
  | sort -u \
  | while read i; do
    ISSUES_ARRAY+=($i)
done

# Make array with issue titles

COUNT=${#ISSUES_ARRAY[@]}
for ((i = 1; i <= $#ISSUES_ARRAY; i++)); do
  NUMBER=${ISSUES_ARRAY[$i]}
  print "($i/$COUNT) Fetching ${LIGHT_GREEN}$NUMBER${NORMAL}"
  TITLE=$(curl -s -u "${USER}:${PASS}" "https://jira.adoreme.com/rest/api/2/issue/$NUMBER?fields=summary" | jq -r .fields.summary)
  TITLES_ARRAY+=($TITLE)
done

print "\n\n${LIGHT_RED}JIRA RELEASE${NORMAL}\n"
print "h1. Release version"
print "Tickets included in this release:\n"
print "h2. Added"
for ((i = 1; i <= $#ISSUES_ARRAY; i++)); do
    NUMBER=${ISSUES_ARRAY[$i]}
    TITLE=${TITLES_ARRAY[$i]}
    printf "* [${LIGHT_GREEN}${NUMBER}${NORMAL}] ${TITLE}\n"
done
print "\nh2. Changed"
print "\nh2. Fixed"

print "\n\n${LIGHT_RED}CHANGELOG.md${NORMAL}\n"
print "## ${REF2} - Name of release\n\n"
print "### Added"
for ((i = 1; i <= $#ISSUES_ARRAY; i++)); do
    NUMBER=${ISSUES_ARRAY[$i]}
    TITLE=${TITLES_ARRAY[$i]}
  printf "* [${LIGHT_GREEN}${NUMBER}${NORMAL}](https://jira.adoreme.com/browse/${LIGHT_GREEN}$NUMBER${NORMAL}) ${TITLE}\n"
done
print ""
print "### Changed\n"
print "### Fixed\n"
