#!/usr/bin/env zsh

print "# Rules for swiftlint version: $(swiftlint version)"
print ""

print "included:"
print " - Sources"
print ""

print "disabled_rules:"
print ""
print "# ---- Autocorrectable rules ----"
print ""

swiftlint rules --config $1 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /no/ && $4 ~ /yes/ && $7 ~ /no/)
		if ($5 ~ /yes/)
			print "# -"$2
		else 
			print " -"$2
}
END {}' \
| sed 's/ *$//'

print ""
print "# ---- Not autocorrectable rules ----"
print ""

swiftlint rules --config $1 \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /no/ && $4 ~ /no/ && $7 ~ /no/) 
		if ($5 ~ /yes/)
			print "# -"$2
		else 
			print " -"$2
}
END {}' \
| sed 's/ *$//'

print ""
print "opt_in_rules:"
print ""
print "# ---- Autocorrectable rules ----"
print ""

swiftlint rules --config $1 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /yes/ && $4 ~ /yes/ && $7 ~ /no/)
		if ($5 ~ /yes/)
			print " -"$2
		else 
			print "# -"$2
}
END {}' \
| sed 's/ *$//'

print ""
print "# ---- Not autocorrectable rules ----"
print ""

swiftlint rules --config $1 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /yes/ && $4 ~ /no/ && $7 ~ /no/) 
		if ($5 ~ /yes/)
			print " -"$2
		else 
			print "# -"$2
}
END {}' \
| sed 's/ *$//'

print ""
print "analyzer_rules:"
print ""

swiftlint rules --config $1 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($7 ~ /yes/) 
		print " -"$2
}
END {}' \
| sed 's/ *$//'
