#!/usr/bin/env zsh

print "included:
  - AdoreMe
  - AdoreMeServiceExtension
  - AdoreMeUnitTests"
print ""

print "disabled_rules:"
print ""
print "# ---- Autocorrectable rules ----"
print ""

swiftlint rules \
| tail +4 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /no/ && $4 ~ /yes/) print "# -"$2
}
END {}'

print ""
print "# ---- Not autocorrectable rules ----"
print ""

swiftlint rules \
| tail +4 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /no/ && $4 ~ /no/) print "# -"$2
}
END {}'

print ""
print "opt_in_rules:"
print ""
print "# ---- Autocorrectable rules ----"
print ""

swiftlint rules \
| tail +4 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /yes/ && $4 ~ /yes/) print "# -"$2
}
END {}'

print ""
print "# ---- Not autocorrectable rules ----"
print ""

swiftlint rules \
| tail +4 \
| sed '$d' \
| awk \
'
BEGIN { FS = "|" }
{
	if ($3 ~ /yes/ && $4 ~ /no/) print "# -"$2
}
END {}'

