#!/usr/bin/env zsh

heading 'Updating Ruby gems ...'
gem update --system --no-document
heading 'Upgrading brew ...'
brew upgrade && brew upgrade --cask
heading 'Updating cocoapods ...'
pod repo update
