#!/usr/bin/env zsh

heading "Reactivating skipped files from git"

is_git_folder || exit 1

TOP_LEVEL_DIR="$(git rev-parse --show-toplevel)"

FILES=$(git -C $TOP_LEVEL_DIR ls-files -v | grep '^S' | cut -d ' ' -f 2 | wc -l)

if (( FILES > 0 )); then
    git -C $TOP_LEVEL_DIR ls-files -v | grep '^S' | cut -d ' ' -f 2
    print ""
    git -C $TOP_LEVEL_DIR ls-files -v | grep '^S' | cut -d ' ' -f 2 | xargs git -C $TOP_LEVEL_DIR update-index --no-skip-worktree
else
    print "${LIGHT_GREEN}* Nothing to reactivate.${NORMAL}"
fi
