#!/usr/bin/env zsh

sudo xcode-select -s "/Applications/Xcode-11.7.0.app/Contents/Developer"
ln -s ~/.dotfiles/xcode/keybindings/Mihai.idekeybindings ~/Library/Developer/Xcode/UserData/KeyBindings/Mihai.idekeybindings
