#!/usr/bin/env zsh

sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
cp ~/.dotfiles/xcode/keybindings/Custom11.idekeybindings ~/Library/Developer/Xcode/UserData/KeyBindings/Mihai.idekeybindings
