#!/usr/bin/env zsh

sudo xcode-select -s "/Applications/Xcode12.2-beta3.app/Contents/Developer"
ln -s ~/.dotfiles/xcode/keybindings/Mihai.idekeybindings ~/Library/Developer/Xcode/UserData/KeyBindings/Mihai.idekeybindings
