#!/usr/bin/env zsh

search_alternatives=()
search_alternatives+=("color key.*name=")
search_alternatives+=("namedColor name=")
search_alternatives+=("<customFonts key=")
regular_expression="(${(j:|:)search_alternatives})"

components=("grep")
components+=("-r")  
components+=("--include \*.storyboard")
components+=("--include \*.xib")
components+=("-E \"$regular_expression\"")

if [[ "$1" == "-f" ]]; then
    components+=("-l")    
fi

components+=("Sources")

if [[ "$1" == "-f" ]]; then
	awk_command='{ print "\"" $0 "\"" }'
	components+=("| awk '$awk_command'")	
else
	awk_command='{gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2); print "\"" $1 "\"" " " "\033[34m" $2 "\033[0m"}'
	components+=("| awk -F ':\s*' '$awk_command'")	
fi

command="${(j: :)components}"
eval $command