#!/usr/bin/env zsh

if [[ -z "$1" ]]; then
	echo "Error: Must provide an argument, the search term."
	exit 1
fi

components=("grep")
components+=("-r")  
components+=("--include \*.storyboard")
components+=("--include \*.xib")
components+=("-E \"$1\"")
components+=("Sources")
components+=('| awk -F '\'':\s*'\'' '\''{ gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2); gsub(/'"$1"'/, "\033[31m" "'"$1"'" "\033[34m", $2); print "\"" $1 "\"" " " "\033[34m" $2 "\033[0m" }'\''')	

command="${(j: :)components}"
# echo $command
eval $command