# Rules for swiftlint version: 0.54.0

included:
 - Sources

disabled_rules:

# ---- Autocorrectable rules ----

# - closing_brace
# - colon
# - comma
# - comment_spacing
# - control_statement
# - duplicate_imports
# - empty_enum_arguments
# - empty_parameters
# - empty_parentheses_with_trailing_closure
# - leading_whitespace
# - legacy_cggeometry_functions
# - legacy_constant
# - legacy_constructor
# - legacy_nsgeometry_functions
# - mark
# - no_space_in_method_call
 - opening_brace
# - private_over_fileprivate
 - private_unit_test
# - protocol_property_accessors_order
# - redundant_discardable_let
# - redundant_objc_attribute
# - redundant_optional_initialization
# - redundant_void_return
# - return_arrow_whitespace
# - statement_position
# - syntactic_sugar
# - trailing_comma
# - trailing_newline
# - trailing_semicolon
# - trailing_whitespace
# - unneeded_break_in_switch
# - unneeded_override
# - unneeded_synthesized_initializer
# - unused_closure_parameter
# - unused_control_flow_label
# - vertical_whitespace
# - void_return

# ---- Not autocorrectable rules ----

# - blanket_disable_command
 - block_based_kvo
# - class_delegate_protocol
 - closure_parameter_position
# - compiler_protocol_init
# - computed_accessors_order
 - custom_rules
 - cyclomatic_complexity
# - deployment_target
# - discouraged_direct_init
# - duplicate_conditions
# - duplicate_enum_cases
# - duplicated_key_in_dictionary_literal
 - dynamic_inline
 - file_length
 - for_where
 - force_cast
 - force_try
 - function_body_length
 - function_parameter_count
 - generic_type_name
 - identifier_name
# - implicit_getter
 - inclusive_language
# - invalid_swiftlint_command
# - is_disjoint
 - large_tuple
 - legacy_hashing
# - legacy_random
 - line_length
# - multiple_closures_with_trailing_closure
 - nesting
# - no_fallthrough_only
# - notification_center_detachment
# - ns_number_init_as_function_reference
# - nsobject_prefer_isequal
# - operator_whitespace
# - orphaned_doc_comment
# - reduce_boolean
# - redundant_set_access_control
# - redundant_string_enum_value
# - self_in_property_initialization
# - shorthand_operator
# - superfluous_disable_command
# - switch_case_alignment
 - todo
 - type_body_length
 - type_name
# - unavailable_condition
# - unused_enumerated
# - unused_optional_binding
# - unused_setter_value
# - valid_ibinspectable
# - vertical_parameter_alignment
# - void_function_in_ternary
 - xctfail_message

opt_in_rules:

# ---- Autocorrectable rules ----

# - anyobject_protocol
 - closure_end_indentation
# - closure_spacing
# - comma_inheritance
# - direct_return
# - explicit_init
 - implicit_return
 - joined_default_parameter
 - literal_expression_end_indentation
# - lower_acl_than_parent
 - modifier_order
 - nimble_operator
# - non_overridable_class_declaration
 - number_separator
 - operator_usage_whitespace
 - optional_enum_case_matching
 - period_spacing
 - prefer_self_in_static_references
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
 - redundant_nil_coalescing
# - redundant_self_in_closure
 - redundant_type_annotation
# - self_binding
# - shorthand_optional_binding
# - sorted_imports
# - strong_iboutlet
 - test_case_accessibility
 - toggle_bool
 - unneeded_parentheses_in_closure_argument
 - untyped_error_in_catch
# - vertical_whitespace_between_cases
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces

# ---- Not autocorrectable rules ----

# - accessibility_label_for_image
# - accessibility_trait_for_button
# - anonymous_argument_in_multiline_closure
 - array_init
# - attributes
 - balanced_xctest_lifecycle
# - closure_body_length
 - collection_alignment
# - conditional_returns_on_newline
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
# - convenience_type
# - discarded_notification_center_observer
# - discouraged_assert
# - discouraged_none_name
# - discouraged_object_literal
# - discouraged_optional_boolean
# - discouraged_optional_collection
 - empty_collection_literal
# - empty_count
 - empty_string
 - empty_xctest_method
# - enum_case_associated_values_count
# - expiring_todo
# - explicit_acl
# - explicit_enum_raw_value
# - explicit_top_level_acl
# - explicit_type_interface
# - extension_access_modifier
 - fallthrough
# - fatal_error_message
# - file_header
# - file_name
 - file_name_no_space
# - file_types_order
# - first_where
# - flatmap_over_map_reduce
# - force_unwrapping
# - function_default_parameter_at_end
# - ibinspectable_in_extension
 - identical_operands
# - implicitly_unwrapped_optional
 - indentation_width
# - inert_defer
 - last_where
 - legacy_multiple
# - legacy_objc_type
 - let_var_whitespace
# - local_doc_comment
# - missing_docs
# - multiline_arguments
# - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
# - multiline_parameters
 - multiline_parameters_brackets
 - no_extension_access_modifier
# - no_grouping_extension
# - no_magic_numbers
# - nslocalizedstring_key
# - nslocalizedstring_require_bundle
# - object_literal
# - overridden_super_call
# - override_in_extension
 - pattern_matching_keywords
# - prefer_nimble
# - prefixed_toplevel_constant
# - private_action
# - private_outlet
# - private_subject
# - private_swiftui_state
# - prohibited_interface_builder
 - prohibited_super_call
# - quick_discouraged_call
# - quick_discouraged_focused_test
# - quick_discouraged_pending_test
 - raw_value_for_camel_cased_codable_enum
# - reduce_into
# - required_deinit
 - required_enum_case
# - return_value_from_void_function
 - single_test_class
# - sorted_enum_cases
# - sorted_first_last
 - static_operator
# - strict_fileprivate
# - superfluous_else
# - switch_case_on_newline
# - trailing_closure
# - type_contents_order
# - unavailable_function
# - unhandled_throwing_task
# - unowned_variable_capture
# - unused_capture_list
 - vertical_parameter_alignment_on_call
# - weak_delegate
# - xct_specific_matcher
 - yoda_condition

analyzer_rules:

 - capture_variable
 - explicit_self
 - typesafe_array_init
 - unused_declaration
 - unused_import
