included:
  - AdoreMe
  - AdoreMeServiceExtension
  - AdoreMeUnitTests

disabled_rules:

# ---- Autocorrectable rules ----

#  - closing_brace
#  - colon
#  - comma
#  - control_statement
#  - empty_enum_arguments
#  - empty_parameters
#  - empty_parentheses_with_trailing_closure
#  - leading_whitespace
#  - legacy_cggeometry_functions
#  - legacy_constant
#  - legacy_constructor
#  - legacy_nsgeometry_functions
#  - mark
#  - no_space_in_method_call
#  - opening_brace
#  - private_over_fileprivate
#  - protocol_property_accessors_order
#  - redundant_discardable_let
#  - redundant_objc_attribute
#  - redundant_optional_initialization
#  - redundant_void_return
#  - return_arrow_whitespace
#  - statement_position
#  - syntactic_sugar
#  - trailing_comma
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - unused_closure_parameter
#  - unused_control_flow_label
#  - vertical_whitespace
#  - void_return
 - weak_delegate

# ---- Not autocorrectable rules ----

#  - block_based_kvo
#  - class_delegate_protocol
#  - closure_parameter_position
#  - compiler_protocol_init
#  - computed_accessors_order
#  - custom_rules
#  - cyclomatic_complexity
#  - deployment_target
#  - discarded_notification_center_observer
#  - discouraged_direct_init
#  - duplicate_enum_cases
#  - duplicate_imports
#  - dynamic_inline
#  - file_length
#  - for_where
 - force_cast
#  - force_try
#  - function_body_length
#  - function_parameter_count
#  - generic_type_name
 - identifier_name
#  - implicit_getter
#  - inclusive_language
#  - inert_defer
#  - is_disjoint
#  - large_tuple
#  - legacy_hashing
 - line_length
#  - multiple_closures_with_trailing_closure
#  - nesting
#  - no_fallthrough_only
#  - notification_center_detachment
#  - nsobject_prefer_isequal
#  - operator_whitespace
#  - orphaned_doc_comment
#  - private_unit_test
#  - reduce_boolean
#  - redundant_set_access_control
#  - redundant_string_enum_value
 - shorthand_operator
#  - superfluous_disable_command
#  - switch_case_alignment
#  - todo
#  - type_body_length
#  - type_name
#  - unneeded_break_in_switch
#  - unused_capture_list
#  - unused_enumerated
#  - unused_optional_binding
#  - unused_setter_value
#  - valid_ibinspectable
#  - vertical_parameter_alignment
#  - xctfail_message

opt_in_rules:

# ---- Autocorrectable rules ----

 - anyobject_protocol
 - closure_end_indentation
 - closure_spacing
 - explicit_init
 - explicit_self
 - implicit_return
 - joined_default_parameter
 - literal_expression_end_indentation
 - modifier_order
 - nimble_operator
 - number_separator
 - operator_usage_whitespace
 - optional_enum_case_matching
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
 - redundant_nil_coalescing
 - redundant_type_annotation
 - sorted_imports
 - toggle_bool
 - unneeded_parentheses_in_closure_argument
 - untyped_error_in_catch
 - unused_import
 - vertical_whitespace_between_cases
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces

# ---- Not autocorrectable rules ----

#  - array_init
#  - attributes
#  - closure_body_length
#  - collection_alignment
#  - conditional_returns_on_newline
#  - contains_over_filter_count
#  - contains_over_filter_is_empty
#  - contains_over_first_not_nil
#  - contains_over_range_nil_comparison
#  - convenience_type
#  - discouraged_object_literal
#  - discouraged_optional_boolean
#  - discouraged_optional_collection
#  - empty_collection_literal
#  - empty_count
#  - empty_string
#  - empty_xctest_method
#  - enum_case_associated_values_count
#  - expiring_todo
#  - explicit_acl
#  - explicit_enum_raw_value
#  - explicit_top_level_acl
#  - explicit_type_interface
#  - extension_access_modifier
#  - fallthrough
#  - fatal_error_message
#  - file_header
#  - file_name
#  - file_name_no_space
#  - file_types_order
#  - first_where
#  - flatmap_over_map_reduce
#  - force_unwrapping
#  - function_default_parameter_at_end
#  - ibinspectable_in_extension
#  - identical_operands
#  - implicitly_unwrapped_optional
#  - indentation_width
#  - last_where
#  - legacy_multiple
#  - legacy_random
#  - let_var_whitespace
#  - lower_acl_than_parent
#  - missing_docs
#  - multiline_arguments
#  - multiline_arguments_brackets
#  - multiline_function_chains
#  - multiline_literal_brackets
#  - multiline_parameters
#  - multiline_parameters_brackets
#  - no_extension_access_modifier
#  - no_grouping_extension
#  - nslocalizedstring_key
#  - nslocalizedstring_require_bundle
#  - object_literal
#  - overridden_super_call
#  - override_in_extension
#  - pattern_matching_keywords
#  - prefer_nimble
#  - prefixed_toplevel_constant
#  - private_action
#  - private_outlet
#  - prohibited_interface_builder
#  - prohibited_super_call
#  - quick_discouraged_call
#  - quick_discouraged_focused_test
#  - quick_discouraged_pending_test
#  - raw_value_for_camel_cased_codable_enum
#  - reduce_into
#  - required_deinit
#  - required_enum_case
#  - single_test_class
#  - sorted_first_last
#  - static_operator
#  - strict_fileprivate
#  - strong_iboutlet
#  - switch_case_on_newline
#  - test_case_accessibility
#  - trailing_closure
#  - type_contents_order
#  - unavailable_function
#  - unowned_variable_capture
#  - unused_declaration
#  - vertical_parameter_alignment_on_call
#  - xct_specific_matcher
#  - yoda_condition

line_length:
  warning: 180
  error: 400
  ignores_comments: true