excluded:
 - build/
 - DerivedData/

opt_in_rules: all
analyzer_rules: all
 
indentation_width:
  indentation_width: 2

disabled_rules:
  - accessibility_label_for_image
  - anonymous_argument_in_multiline_closure
  - attributes
  - blanket_disable_command
  - contrasted_opening_brace
  - direct_return
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - identifier_name
  - missing_docs
  - nesting
  - no_empty_block
  - no_magic_numbers
  - required_deinit
  - sorted_enum_cases
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - trailing_comma
  - type_contents_order

